import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
// import CustomCursor from "@/components/custom-cursor";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" style={{ scrollBehavior: "smooth" }}>
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <div className="flex flex-col bg-black min-h-screen items-center relative  text-white">
          {/* <CustomCursor /> */}
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
